# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build stone.json

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Build stone.json
      run: yarn run gulp
    - name: Upload stone.json as artifact
      uses: actions/upload-artifact@v1
      with:
          name: stone.json
          path: dist/stone.json
    - name: Upload stone.dist.json as artifact
      uses: actions/upload-artifact@v1
      with:
          name: stone.dist.json
          path: dist/stone.dist.json
